import '../models/category_model.dart';
import '../models/word_model.dart';

class InitialSeedData {
  static final List<CategoryModel> categories = [
    CategoryModel(
      id: 1,
      name: 'Temel Seviye',
      description: 'Başlangıç seviyesi en sık kullanılan kelimeler',
      iconName: 'school',
      colorHex: '#4F46E5',
    ),
    CategoryModel(
      id: 2,
      name: 'Günlük Konuşma',
      description: 'Günlük hayatta karşınıza çıkacak ifadeler',
      iconName: 'chat',
      colorHex: '#0EA5E9',
    ),
    CategoryModel(
      id: 3,
      name: 'Fiiller',
      description: 'En yaygın kullanılan eylemler ve çekimleri',
      iconName: 'flash',
      colorHex: '#F59E0B',
    ),
    CategoryModel(
      id: 4,
      name: 'Sıfatlar',
      description: 'Durum ve özellikleri niteleyen kelimeler',
      iconName: 'palette',
      colorHex: '#10B981',
    ),
    CategoryModel(
      id: 5,
      name: 'İş & Kariyer',
      description: 'Profesyonel iş hayatı ve mülakat terimleri',
      iconName: 'work',
      colorHex: '#8B5CF6',
    ),
    CategoryModel(
      id: 6,
      name: 'Sınav & YDS',
      description: 'YDS, YÖKDİL ve TOEFL için ileri seviye kelimeler',
      iconName: 'trophy',
      colorHex: '#EC4899',
    ),
    CategoryModel(
      id: 7,
      name: 'Seyahat & Tatil',
      description: 'Havalimanı, otel ve gezi kelimeleri',
      iconName: 'flight',
      colorHex: '#14B8A6',
    ),
  ];

  static final List<WordModel> words = [
    // Temel Seviye
    WordModel(
      id: 1,
      english: 'Achieve',
      turkish: 'Başarmak, Elde etmek',
      category: 'Temel Seviye',
      phonetic: '/əˈtʃiːv/',
      definition: 'To successfully complete something or reach a goal especially by effort.',
      exampleSentence: 'She worked hard to achieve her dreams.',
      exampleSentenceTr: 'Hayallerine ulaşmak için çok sıkı çalıştı.',
      difficulty: 2,
    ),
    WordModel(
      id: 2,
      english: 'Opportunity',
      turkish: 'Fırsat, Olanak',
      category: 'Temel Seviye',
      phonetic: '/ˌɒp.əˈtʃuː.nə.ti/',
      definition: 'A set of circumstances that makes it possible to do something.',
      exampleSentence: 'This job is a great opportunity for learning.',
      exampleSentenceTr: 'Bu iş öğrenmek için harika bir fırsattır.',
      difficulty: 2,
    ),
    WordModel(
      id: 3,
      english: 'Challenge',
      turkish: 'Meydan okuma, Zorluk',
      category: 'Temel Seviye',
      phonetic: '/ˈtʃæl.ɪndʒ/',
      definition: 'A call to take part in a contest or difficult task.',
      exampleSentence: 'Learning a new language is a fun challenge.',
      exampleSentenceTr: 'Yeni bir dil öğrenmek eğlenceli bir meydan okumadır.',
      difficulty: 2,
    ),
    WordModel(
      id: 4,
      english: 'Improve',
      turkish: 'Geliştirmek, İyileşmek',
      category: 'Temel Seviye',
      phonetic: '/ɪmˈpruːv/',
      definition: 'To make or become better.',
      exampleSentence: 'Reading books will improve your vocabulary.',
      exampleSentenceTr: 'Kitap okumak kelime dağarcığını geliştirecektir.',
      difficulty: 1,
    ),
    WordModel(
      id: 5,
      english: 'Knowledge',
      turkish: 'Bilgi, Birikim',
      category: 'Temel Seviye',
      phonetic: '/ˈnɒl.ɪdʒ/',
      definition: 'Facts, information, and skills acquired through experience or education.',
      exampleSentence: 'Knowledge is the greatest power in life.',
      exampleSentenceTr: 'Bilgi hayattaki en büyük güçtür.',
      difficulty: 2,
    ),
    WordModel(
      id: 6,
      english: 'Discover',
      turkish: 'Keşfetmek, Bulmak',
      category: 'Temel Seviye',
      phonetic: '/dɪˈskʌv.ər/',
      definition: 'To find unexpectedly or in the course of a search.',
      exampleSentence: 'Scientists continue to discover new stars in space.',
      exampleSentenceTr: 'Bilim insanları uzayda yeni yıldızlar keşfetmeye devam ediyor.',
      difficulty: 2,
    ),

    // Günlük Konuşma
    WordModel(
      id: 7,
      english: 'Hesitate',
      turkish: 'Tereddüt etmek, Duraksamak',
      category: 'Günlük Konuşma',
      phonetic: '/ˈhez.ɪ.teɪt/',
      definition: 'To pause before saying or doing something that you are unsure about.',
      exampleSentence: 'Do not hesitate to ask if you have any questions.',
      exampleSentenceTr: 'Herhangi bir sorunuz varsa sormaktan çekinmeyin.',
      difficulty: 2,
    ),
    WordModel(
      id: 8,
      english: 'Recommend',
      turkish: 'Tavsiye etmek, Önermek',
      category: 'Günlük Konuşma',
      phonetic: '/ˌrek.əˈmend/',
      definition: 'To suggest that someone or something would be good or suitable.',
      exampleSentence: 'Which Turkish dish would you recommend?',
      exampleSentenceTr: 'Hangi Türk yemeğini tavsiye edersiniz?',
      difficulty: 2,
    ),
    WordModel(
      id: 9,
      english: 'Appreciate',
      turkish: 'Takdir etmek, Minnettar olmak',
      category: 'Günlük Konuşma',
      phonetic: '/əˈpriː.ʃi.eɪt/',
      definition: 'To recognize the full worth of; to be grateful for.',
      exampleSentence: 'I really appreciate your kind help.',
      exampleSentenceTr: 'Nazik yardımınız için gerçekten minnettarım.',
      difficulty: 2,
    ),
    WordModel(
      id: 10,
      english: 'Interrupt',
      turkish: 'Sözünü kesmek, Araya girmek',
      category: 'Günlük Konuşma',
      phonetic: '/ˌɪn.təˈrʌpt/',
      definition: 'To stop the continuous progress of an activity or speech.',
      exampleSentence: 'Sorry to interrupt, but there is an urgent phone call for you.',
      exampleSentenceTr: 'Böldüğüm için özür dilerim ama sizin için acil bir telefon var.',
      difficulty: 3,
    ),
    WordModel(
      id: 11,
      english: 'Familiar',
      turkish: 'Tanıdık, Aşina',
      category: 'Günlük Konuşma',
      phonetic: '/fəˈmɪl.jər/',
      definition: 'Well known from long or close association.',
      exampleSentence: 'Her face looks very familiar to me.',
      exampleSentenceTr: 'Onun yüzü bana çok tanıdık geliyor.',
      difficulty: 2,
    ),

    // Fiiller
    WordModel(
      id: 12,
      english: 'Accomplish',
      turkish: 'Tamamlamak, Başarmak',
      category: 'Fiiller',
      phonetic: '/əˈkʌm.plɪʃ/',
      definition: 'To achieve or complete successfully.',
      exampleSentence: 'You can accomplish anything with dedication.',
      exampleSentenceTr: 'Azimle her şeyi başarabilirsiniz.',
      difficulty: 3,
    ),
    WordModel(
      id: 13,
      english: 'Consider',
      turkish: 'Düşünmek, Göz önünde bulundurmak',
      category: 'Fiiller',
      phonetic: '/kənˈsɪd.ər/',
      definition: 'To think carefully about something, typically before making a decision.',
      exampleSentence: 'Please consider all available options before deciding.',
      exampleSentenceTr: 'Karar vermeden önce lütfen mevcut tüm seçenekleri değerlendirin.',
      difficulty: 2,
    ),
    WordModel(
      id: 14,
      english: 'Persuade',
      turkish: 'İkna etmek, Razı etmek',
      category: 'Fiiller',
      phonetic: '/pəˈsweɪd/',
      definition: 'To cause someone to believe something through reasoning or argument.',
      exampleSentence: 'He tried hard to persuade the team to accept the plan.',
      exampleSentenceTr: 'Ekibi planı kabul etmeye ikna etmek için çok uğraştı.',
      difficulty: 3,
    ),
    WordModel(
      id: 15,
      english: 'Maintain',
      turkish: 'Sürdürmek, Korumak, Bakımını yapmak',
      category: 'Fiiller',
      phonetic: '/meɪnˈteɪn/',
      definition: 'To cause or enable a condition or state of affairs to continue.',
      exampleSentence: 'It is important to maintain a healthy work-life balance.',
      exampleSentenceTr: 'Sağlıklı bir iş-yaşam dengesini korumak önemlidir.',
      difficulty: 3,
    ),
    WordModel(
      id: 16,
      english: 'Overcome',
      turkish: 'Üstesinden gelmek, Aşmak',
      category: 'Fiiller',
      phonetic: '/ˌəʊ.vəˈkʌm/',
      definition: 'To succeed in dealing with a problem or difficulty.',
      exampleSentence: 'With practice, you can overcome your fear of public speaking.',
      exampleSentenceTr: 'Pratik yaparak topluluk önünde konuşma korkunuzun üstesinden gelebilirsiniz.',
      difficulty: 3,
    ),

    // Sıfatlar
    WordModel(
      id: 17,
      english: 'Crucial',
      turkish: 'Çok önemli, Hayati, Kritik',
      category: 'Sıfatlar',
      phonetic: '/ˈkruː.ʃəl/',
      definition: 'Decisive or critical, especially in the success or failure of something.',
      exampleSentence: 'Early preparation is crucial for passing the exam.',
      exampleSentenceTr: 'Sınavı geçmek için erken hazırlık hayati önem taşır.',
      difficulty: 3,
    ),
    WordModel(
      id: 18,
      english: 'Efficient',
      turkish: 'Verimli, Etkili',
      category: 'Sıfatlar',
      phonetic: '/ɪˈfɪʃ.ənt/',
      definition: 'Achieving maximum productivity with minimum wasted effort or expense.',
      exampleSentence: 'This method is the most efficient way to study vocabulary.',
      exampleSentenceTr: 'Bu yöntem kelime çalışmanın en verimli yoludur.',
      difficulty: 2,
    ),
    WordModel(
      id: 19,
      english: 'Inevitable',
      turkish: 'Kaçınılmaz, Önlenemez',
      category: 'Sıfatlar',
      phonetic: '/ɪnˈev.ɪ.tə.bəl/',
      definition: 'Certain to happen; unavoidable.',
      exampleSentence: 'Change is an inevitable part of life.',
      exampleSentenceTr: 'Değişim hayatın kaçınılmaz bir parçasıdır.',
      difficulty: 4,
    ),
    WordModel(
      id: 20,
      english: 'Reliable',
      turkish: 'Güvenilir, İtimat edilir',
      category: 'Sıfatlar',
      phonetic: '/rɪˈlaɪ.ə.bəl/',
      definition: 'Consistently good in quality or performance, able to be trusted.',
      exampleSentence: 'He is a reliable friend whom you can count on.',
      exampleSentenceTr: 'O, güvenebileceğiniz sadık ve güvenilir bir arkadaştır.',
      difficulty: 2,
    ),
    WordModel(
      id: 21,
      english: 'Significant',
      turkish: 'Önemli, Kayda değer, Belirgin',
      category: 'Sıfatlar',
      phonetic: '/sɪɡˈnɪf.ɪ.kənt/',
      definition: 'Sufficiently great or important to be worthy of attention.',
      exampleSentence: 'There has been a significant increase in his scores.',
      exampleSentenceTr: 'Puanlarında kayda değer bir artış oldu.',
      difficulty: 3,
    ),

    // İş & Kariyer
    WordModel(
      id: 22,
      english: 'Negotiate',
      turkish: 'Müzakere etmek, Pazarlık yapmak',
      category: 'İş & Kariyer',
      phonetic: '/nəˈɡəʊ.ʃi.eɪt/',
      definition: 'To obtain or bring about by discussion.',
      exampleSentence: 'The company managed to negotiate a better contract.',
      exampleSentenceTr: 'Şirket daha iyi bir sözleşme için müzakere etmeyi başardı.',
      difficulty: 3,
    ),
    WordModel(
      id: 23,
      english: 'Deadline',
      turkish: 'Son teslim tarihi',
      category: 'İş & Kariyer',
      phonetic: '/ˈded.laɪn/',
      definition: 'The latest time or date by which something should be completed.',
      exampleSentence: 'We must finish the project before Friday\'s deadline.',
      exampleSentenceTr: 'Projeyi Cuma günkü son teslim tarihinden önce bitirmeliyiz.',
      difficulty: 2,
    ),
    WordModel(
      id: 24,
      english: 'Colleague',
      turkish: 'İş arkadaşı, Meslektaş',
      category: 'İş & Kariyer',
      phonetic: '/ˈkɒl.iːɡ/',
      definition: 'A person with whom one works in a profession or business.',
      exampleSentence: 'I discussed the new marketing strategy with my colleagues.',
      exampleSentenceTr: 'Yeni pazarlama stratejisini meslektaşlarımla tartıştım.',
      difficulty: 2,
    ),
    WordModel(
      id: 25,
      english: 'Objective',
      turkish: 'Hedef, Amaç, Tarafsız',
      category: 'İş & Kariyer',
      phonetic: '/əbˈdʒek.tɪv/',
      definition: 'A thing aimed at or sought; a goal.',
      exampleSentence: 'Our primary objective is customer satisfaction.',
      exampleSentenceTr: 'Birincil hedefimiz müşteri memnuniyetidir.',
      difficulty: 3,
    ),
    WordModel(
      id: 26,
      english: 'Revenue',
      turkish: 'Gelir, Kazanç',
      category: 'İş & Kariyer',
      phonetic: '/ˈrev.ən.juː/',
      definition: 'Income, especially when of a company or organization.',
      exampleSentence: 'The annual revenue increased by twenty percent.',
      exampleSentenceTr: 'Yıllık gelir yüzde yirmi arttı.',
      difficulty: 3,
    ),

    // Sınav & YDS
    WordModel(
      id: 27,
      english: 'Abundant',
      turkish: 'Bol, Bereketli, Çok sayıda',
      category: 'Sınav & YDS',
      phonetic: '/əˈbʌn.dənt/',
      definition: 'Existing or available in large quantities; plentiful.',
      exampleSentence: 'The forest provides an abundant source of natural food.',
      exampleSentenceTr: 'Orman bol miktarda doğal gıda kaynağı sağlar.',
      difficulty: 4,
    ),
    WordModel(
      id: 28,
      english: 'Deteriorate',
      turkish: 'Kötüleşmek, Bozulmak',
      category: 'Sınav & YDS',
      phonetic: '/dɪˈtɪə.ri.ə.reɪt/',
      definition: 'To become progressively worse.',
      exampleSentence: 'Air quality began to deteriorate due to pollution.',
      exampleSentenceTr: 'Kirlilik nedeniyle hava kalitesi kötüleşmeye başladı.',
      difficulty: 4,
    ),
    WordModel(
      id: 29,
      english: 'Feasible',
      turkish: 'Uygulanabilir, Makul, Mümkün',
      category: 'Sınav & YDS',
      phonetic: '/ˈfiː.zə.bəl/',
      definition: 'Possible to do easily or conveniently.',
      exampleSentence: 'The engineers proposed a feasible solution to the traffic issue.',
      exampleSentenceTr: 'Mühendisler trafik sorununa uygulanabilir bir çözüm önerdiler.',
      difficulty: 4,
    ),
    WordModel(
      id: 30,
      english: 'Reluctant',
      turkish: 'İsteksiz, Gönülsüz',
      category: 'Sınav & YDS',
      phonetic: '/rɪˈlʌk.tənt/',
      definition: 'Unwilling and hesitant; disinclined.',
      exampleSentence: 'He was reluctant to share his private notes with others.',
      exampleSentenceTr: 'Özel notlarını başkalarıyla paylaşma konusunda isteksizdi.',
      difficulty: 4,
    ),
    WordModel(
      id: 31,
      english: 'Ambiguous',
      turkish: 'Muğlak, Belirsiz, Çift anlamlı',
      category: 'Sınav & YDS',
      phonetic: '/æmˈbɪɡ.ju.əs/',
      definition: 'Open to more than one interpretation; having a double meaning.',
      exampleSentence: 'The wording of the law was ambiguous and caused confusion.',
      exampleSentenceTr: 'Yasanın ifadesi muğlaktı ve kafa karışıklığına yol açtı.',
      difficulty: 5,
    ),

    // Seyahat & Tatil
    WordModel(
      id: 32,
      english: 'Accommodation',
      turkish: 'Konaklama, Kalacak yer',
      category: 'Seyahat & Tatil',
      phonetic: '/əˌkɒm.əˈdeɪ.ʃən/',
      definition: 'A room, group of rooms, or building in which someone may live or stay.',
      exampleSentence: 'We booked our accommodation near the city center.',
      exampleSentenceTr: 'Konaklamamızı şehir merkezine yakın bir yerde ayırttık.',
      difficulty: 2,
    ),
    WordModel(
      id: 33,
      english: 'Departure',
      turkish: 'Kalkış, Ayrılış',
      category: 'Seyahat & Tatil',
      phonetic: '/dɪˈpɑː.tʃər/',
      definition: 'The action of leaving, especially on a journey.',
      exampleSentence: 'Please check the flight departure board carefully.',
      exampleSentenceTr: 'Lütfen uçuş kalkış panosunu dikkatlice kontrol edin.',
      difficulty: 2,
    ),
    WordModel(
      id: 34,
      english: 'Destination',
      turkish: 'Varış noktası, Hedef yer',
      category: 'Seyahat & Tatil',
      phonetic: '/ˌdes.tɪˈneɪ.ʃən/',
      definition: 'The place to which someone or something is going or being sent.',
      exampleSentence: 'Istanbul is one of the world\'s most popular travel destinations.',
      exampleSentenceTr: 'İstanbul dünyanın en popüler seyahat noktalarından biridir.',
      difficulty: 2,
    ),
    WordModel(
      id: 35,
      english: 'Customs',
      turkish: 'Gümrük',
      category: 'Seyahat & Tatil',
      phonetic: '/ˈkʌs.təmz/',
      definition: 'The place at an airport or border where travelers\' bags are checked.',
      exampleSentence: 'It took twenty minutes to pass through airport customs.',
      exampleSentenceTr: 'Havalimanı gümrüğünden geçmek yirmi dakika sürdü.',
      difficulty: 2,
    ),
  ];
}
